name: "Test push to docker hub"

on: 
  workflow_dispatch:
    #inputs:
    #  releasename:
    #    description: Release Version
    #    required: true

jobs:
  build:
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ["icecast"]
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      #- name: List addons
      #  run: |
      #    echo "${{ needs.init.outputs.addons }}"
      - name: Check out repository
        uses: actions/checkout@v2.4.0

      #- name: Get information
      #  id: info
      #  uses: home-assistant/actions/helpers/info@master
      #  with:
      #    path: "./${{ matrix.addon }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}      

      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target ${{ matrix.addon }} \
            --docker-hub mohankumargupta

