name: "Test push to docker hub"

on: 
  workflow_dispatch:
    #inputs:
    #  releasename:
    #    description: Release Version
    #    required: true

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: List addons
        run: |
         echo "${{ needs.init.outputs.architectures }}"
#      - name: Test build
#        uses: home-assistant/builder@master
#        with:
#          args: |
#            --test \
#            --all \
#            --target icecast \
#            --docker-hub mohankumargupta

