name: "Test push to docker hub"

on: 
  workflow_dispatch:
    #inputs:
    #  releasename:
    #    description: Release Version
    #    required: true

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Get add-ons
        id: addons
        run: |
          declare -a addons
          for addon in $(find ./ -name config.yaml | cut -d "/" -f2 | sort -u); do
            addons+=("$addon");
          done
          echo "::set-output name=addons::${addons[@]}"
      - name: List add-ons
        run: |
          ls -l 
          find ./ -name config.yaml  
#      - name: Get information
#        id: info
#        uses: home-assistant/actions/helpers/info@master
#      - name: Test build
#        uses: home-assistant/builder@master
#        with:
#          args: |
#            --test \
#            --all \
#            --target icecast \
#            --docker-hub mohankumargupta

