name: "Test push to docker hub"

on: 
  workflow_dispatch:
    #inputs:
    #  releasename:
    #    description: Release Version
    #    required: true

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.info.outputs.addons }}    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Get add-ons
        id: addons
        run: |
          declare -a addons
          for addon in $(find ./ -name config.yaml | cut -d "/" -f2 | sort -u); do
            addons+=("$addon");
          done
          echo "::set-output name=addons::${addons[@]}"
  build:
    name: Build
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: List addons
        run: |
         echo "${{ needs.init.outputs.addons }}"
#      - name: Test build
#        uses: home-assistant/builder@master
#        with:
#          args: |
#            --test \
#            --all \
#            --target icecast \
#            --docker-hub mohankumargupta

