name: "Test push to docker hub"

on: 
  workflow_dispatch:
    inputs:
      releasename:
        description: Release Version
        required: true

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target icecast \
            --docker-hub mohankumargupta

